name = "AirSeaFluxes"
uuid = "3dfee02d-11ce-464a-9ee1-cf3f5c5ccad7"
authors = ["gaelforget <gforget@mit.edu>"]
version = "0.1.3"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Dierckx = "0.4"
julia = "1"
